### ISSUE TITLE
应用内切换主题实现案例

### ISSUE THREAD

**Issue by yansha87** [ZhaoKaiQiang/AndroidDifficultAnalysis#1]
`应用内切换主题有哪些方案可以实现`写的挺好的，建议加上[NightOwl](https://github.com/ashqal/NightOwl)的实现案例，虽然和AndroidChangeSkin思路类似，但实现却有很多值得学习借鉴的地方

**Comment by ZhaoKaiQiang** [comment]
多谢，已添加项目链接，AndroidChangeSkin其实也是借鉴Android-skin-load的思路，所以一个类型就只列出了一个
