### ISSUE TITLE
设计模式中还有一个组合模式没提到

### ISSUE THREAD

**Issue by xu6148152** [ZhaoKaiQiang/AndroidDifficultAnalysis#3]
Android 中所有的View都是采用这种模式来设计的。
还有备忘录模式,Android 的canvas画图很多地方都会采用这种模式。

**Comment by ZhaoKaiQiang** [comment]
这里只整理了我认为比较重要的设计模式，所以好多模式没写，包括但不限于你提到的组合模式、备忘录模式、桥接模式、适配器模式、解释器模式等等，一方面是对某些模式理解不够深， 另一方面是没有深刻体会到带来的好处，所以就没写。

如果你对某种模式理解比较深刻的话，可以提交request，我会merge的！

**Comment by helloworld10010** [comment]
> 这里只整理了我认为比较重要的设计模式，所以好多模式没写，包括但不限于你提到的组合模式、备忘录模式、桥接模式、适配器模式、解释器模式等等，一方面是对某些模式理解不够深， 另一方面是没有深刻体会到带来的好处，所以就没写。
> 
> 如果你对某种模式理解比较深刻的话，可以提交request，我会merge的！

你提到的‘书中’是指啥书？
